services:
  jellyfin-auto-collections:
    build: .
    container_name: jellyfin-auto-collections
    environment:
      - CRONTAB=0 * * * *
      - TZ=America/New_York
    volumes:
      - ${CONFIG_DIR}/jellyfin-auto-collections/config:/app/config
    restart: unless-stopped
